mode = "dark"

accent = "#5EB7FF"
selection = "#26343F"
muted = "#34363A"

background = "#1A1D23"
dark_background = "#111317"
darker_background = "#0B0C0F"
lighter_background = "#26343F"

foreground = "#9B9FA9"
dark_foreground = "#6B6F79"
light_foreground = "#B8BCC6"
bright_foreground = "#D0D3DE"

red = "#FF838B"
yellow = "#DFAB25"
orange = "#E8925A"
green = "#87C05F"
cyan = "#4AC2B8"
blue = "#5EB7FF"
magenta = "#DD97F1"
brown = "#7A5240"

bright_red = "#FFA6AE"
bright_yellow = "#FFCE48"
bright_green = "#AAE382"
bright_cyan = "#6DE5DB"
bright_blue = "#81DAFF"
bright_magenta = "#FFBAFF"

cursor = "#9B9FA9"
selection_foreground = "#9B9FA9"
selection_background = "#26343F"
